# custom-resources/pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi  # Specify the desired storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "gp2"  # Update with your StorageClass
  awsElasticBlockStore:
    volumeID: vol-0c48495c98f0d0046  # Replace with your EBS volume ID
